image:
  file: .gitpod.Dockerfile

ports:
  # django server
  - port: 8000
    onOpen: open-preview
  - port: 8025
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore


tasks:
  - init: 'export PIP_USER=false && export CELERY_BROKER_URL=redis://localhost:6379/0 && pip install -r server/requirements/local.txt && pre-commit install && source server/.envs/.local/.django  && source server/.envs/.local/.postgres && psql -c "CREATE DATABASE server"  && python manage.py migrate'
    command: 'cd server && python manage.py runserver'
  - command: 'redis-server'
  - command: 'MailHog'
    # command: 'createdb server -U postgres --password $POSTGRES_PASSWORD'
