image:
  file: .gitpod.Dockerfile

ports:
  # django server
  - port: 8080
    # onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore


tasks:
  - init: 'pip install -r requirements/local.txt && pre-commit install && source server/.envs/.local/.django  && source server/.envs/.local/.postgres'
    command: 'createdb server -U postgres --password $POSTGRES_PASSWORD'
