
image:
  file: .gitpod.Dockerfile

ports:
  # django server
  - port: 8000
    onOpen: open-preview
  - port: 8025
    onOpen: open-preview
  # PostgreSQL server
  - port: 5432
    onOpen: ignore


tasks:
  - name: Server
    init: cd server && pip install -r requirements/local.txt && pre-commit install && source .envs/.local/.django  && source .envs/.local/.postgres && psql -c "CREATE DATABASE server"
  - name: Vue Client
    init: cd client && yarn && cd ..
    command: cd client && yarn serve
  - command: 'redis-server'
  - command: 'MailHog'
  # command: 'createdb server -U postgres --password $POSTGRES_PASSWORD'

#vscode:
#  extensions:
#    - vsls-contrib.codetour

github:
  prebuilds:
    master: false